version: '3.9'

services:
  gateway:
    build: MySpace.Gateway
    hostname: gateway
    container_name: gateway
    ports:
      - "8000:80"

  mongo:
    image: mongo:5.0
    hostname: mongo
    container_name: mongo
    volumes:
      - ~/apps/mongo:/data/db

  api:
    build: MySpace.Api
    hostname: api
    container_name: api
        
  authentication-service:
    build: MySpace.Authentication
    hostname: authentication-service
    container_name: authentication-service