version: '3.9'

services:
  mongo:
    image: mongo:5.0
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - db-service

  api:
    build: MySpace.Api
    hostname: api
    container_name: api
    depends_on:
      - mongo
    volumes:
      - ./cert/nginx/letsencrypt/live/mohammed.ezzedine.me:/https/
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.pem
    networks:
      - gateway-internal
      - db-service
        
  authentication-service:
    build: MySpace.Authentication
    hostname: authentication-service
    container_name: authentication-service
    depends_on:
      - mongo
    volumes:
      - ./cert/nginx/letsencrypt/live/mohammed.ezzedine.me:/https/
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.pem
    networks:
      - gateway-internal
      - db-service
    
  ui:
    build: MySpace
    hostname: ui
    container_name: ui
    volumes:
      - ./MySpace:/app
      - /MySpace/node_modules
      - ./cert/nginx/letsencrypt:/etc/letsencrypt
      - ./cert/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
    networks:
      - client-gateway
      
  proxy:
    build: MySpace.Proxy
    hostname: proxy
    container_name: proxy
    networks:
      - client-gateway
      - gateway-internal
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./cert/nginx/letsencrypt:/etc/letsencrypt
      - ./cert/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
        
networks:
  client-gateway:
    name: client-gateway-network
  gateway-internal:
    name: gateway-internal-network
  db-service:
    name: db-service-network